config/routes.rb
Rails.application.routes.draw do
  root "homes#top"
  get "/about" => "homes#about"
  get "public/questions/search" => "public/questions#search"
  post 'questions/:question_id/likes' => "likes#create"
  delete 'questions/:question_id/likes' => "likes#destroy"

  #deviseのcontrollerを二つ作ったため、それぞれのルーティングが必要
  devise_for :admins, :controllers => {
    :sessions => 'admin/devise/sessions'
  }
  devise_for :customers, :controllers => {
    :sessions => 'public/devise/sessions',
    :registrations => 'public/devise/registrations'
  }

#namespaceを用いてpublicとadminのルーティングを指定
    namespace :public do
    	resources :questions, only: [:index, :new, :create, :update, :edit]
    	resources :choices
      resources :customers
      get "customers/like/customer_id" => "customers#like"
      resources :genres, only: [:index] do
        resources :questions, only: [:index]
      end
      resources :tags, only: [:index] do
        resources :questions, only: [:index]
      end
    end 


    namespace :admin do
      get "questions/allow" => "questions#allow"
    	resources :questions, only: [:index, :new, :create, :update, :edit]
    	resources :choices
      resources :customers, only: [:index, :show]
      resources :genres, only: [:index, :create, :edit, :update] do
        resources :questions, only: [:index]
      end
      resources :tags, only: [:index] do
        resources :questions, only: [:index]
      end
    end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
	belongs_to :question, optional: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
    has_many :questions
    has_many :likes, dependent: :destroy
    has_many :liked_question, through: :likes, source: :question

   attachment :image
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :questions
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :question
  belongs_to :customer
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :choices, dependent: :destroy
	has_many :likes
	has_many :question_tags
	accepts_nested_attributes_for :choices #question作成時にchoiceも同時生成
	belongs_to :customer, optional: true
	belongs_to :genre
	attachment :image

	enum is_allowed:{
		許可待ち: 0,
		不許可: 1,
		許可: 2,
	}, _suffix: true
end

app/models/question_tag.rb
class QuestionTag < ApplicationRecord
	belongs_to :question
	belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :question_tags
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
	before_action :authenticate_admin!
	def index
		@customers = Customer.all
	end

	def show
		@customer = Customer.find(params[:id])
		@question = Question.where(customer_id:@customer).order(id: "DESC")
	end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
	before_action :authenticate_admin!
	def index
		@genres = Genre.all
		@genre = Genre.new
	end

	def create
		@genre = Genre.new(genre_params)
		@genres = Genre.all
		if @genre.save
		   redirect_back(fallback_location: root_path)
		else
		   render :index
		end
	end

	def edit
		@genre = Genre.find(params[:id])
	end

	def update
		@genre = Genre.find(params[:id])
		@genre.update(genre_params)
		redirect_to admin_genres_path
	end

	private
    def genre_params
    	params.require(:genre).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
	def after_sign_in_path_for(resource)#ログイン後のpassを指定
		if customer_signed_in?#会員ならば
    	   public_customer_path(resource)
    	else
    	   admin_questions_path#管理者ならば
        end
    end

    def after_sign_out_path_for(resource)
		root_path(resource)
	end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :set_question

    def create
      @like = Like.create(customer_id: current_customer.id, question_id: @question.id)
      @question = Question.find(params[:question_id])
    end

    def destroy
      @like = Like.find_by(customer_id: current_customer.id, question_id: @question.id)
      @like.destroy
    end

    private
    def set_question
      @question = Question.find(params[:question_id])
    end
end

app/helpers/admin/choices_helper.rb
module Admin::ChoicesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/admin/customers/index.html.erb
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<P>会員一覧</P>
		<table class="table table-hover">
			<thead>
				<tr class="active">
					<th>会員ID</th>
					<th>ユーザ名</th>
					<th>Email</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			    <% @customers.each do |customer| %>
			    <tr>
			    	<td>
			    		<%= customer.id %>
			    	</td>
			    	<td>
			    		<%= customer.name %>
			    	</td>
			    	<td>
			    		<%= customer.email %>
			    	</td>
			    	<td>
			    		<%= link_to "クイズ一覧", admin_customer_path(customer) %>
			    	</td>
			    </tr>
			    <% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/admin/customers/show.html.erb
<div class="row">
	<div class="main-top"></div>
	<div style="margin-top: 3%; ">
		<table class="col-xs-2 col-xs-offset-1">
			<tr style="border-bottom: solid black 1px;">
				<th>Name</th>
				<th><%= @customer.name %></th>
			</tr>
			<tr style="border-bottom: solid black 1px;">
				<th>Email</th>
				<th><%= @customer.email %></th>
			</tr>
		</table>
		<div class="col-xs-6 col-xs-offset-1">
			<p><%= @customer.name %>さんが作成したクイズ一覧</p>
			<div>
			<% @question.each do |question| %>
			    <div class="question-solve">
			    	<div>
    					<%= attachment_image_tag question, :image, class: "img-square", size:"300x200" %>
					</div>
			    	<div class="question-content">
			    		Q.
			    		<%= question.content %>
			    	</div>
			    	<div>
			    		<% question.choices.each do |choice| %>
			    			<div class="check btn btn-info btn-block question-choice">
			    		    	<%= choice.sentence %>
			    		    </div>
			    		<% end %>
			    	</div>
			    	<div class="row">
			    		<div class="question-genre col-xs-3">
			    			<%= question.genre.name %>
			    		</div>
			    		<% question.question_tags.each do |question_tag| %>
                      		<div class="question-tag"><%= question_tag.tag.name %></div>
                    	<% end %>
			    	</div>
			    	<div class="comment question-comment">
			    		<% question.choices.each do |choice| %>
			    			<% if choice.is_answer == true %>
			    		    	<div>正解は　<%= choice.sentence %>　！</div>
			    			<% end %>
			    		<% end %>
			    		解説<br>
			    		<%= question.comment %><br>
			    		<%= link_to "編集する", edit_public_question_path(question), {class: 'btn btn-success'} %>
			    	</div>
			    </div>
			<% end %>
			</div>
		</div>
	</div>
</div>
<div class="main-bottom" style="margin-top: 3%;"></div>