config/routes.rb
Rails.application.routes.draw do
  root "homes#top"
  get "/about" => "homes#about"
  get "public/questions/search" => "public/questions#search"
  post 'questions/:question_id/likes' => "likes#create"
  delete 'questions/:question_id/likes' => "likes#destroy"

  #deviseのcontrollerを二つ作ったため、それぞれのルーティングが必要
  devise_for :admins, :controllers => {
    :sessions => 'admin/devise/sessions'
  }
  devise_for :customers, :controllers => {
    :sessions => 'public/devise/sessions',
    :registrations => 'public/devise/registrations'
  }

#namespaceを用いてpublicとadminのルーティングを指定
    namespace :public do
    	resources :questions, only: [:index, :new, :create, :update, :edit]
    	resources :choices
      resources :customers
      get "customers/like/customer_id" => "customers#like"
      resources :genres, only: [:index] do
        resources :questions, only: [:index]
      end
      resources :tags, only: [:index] do
        resources :questions, only: [:index]
      end
    end 


    namespace :admin do
      get "questions/allow" => "questions#allow"
    	resources :questions, only: [:index, :new, :create, :update, :edit]
    	resources :choices
      resources :customers, only: [:index, :show]
      resources :genres, only: [:index, :create, :edit, :update] do
        resources :questions, only: [:index]
      end
      resources :tags, only: [:index] do
        resources :questions, only: [:index]
      end
    end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
	belongs_to :question, optional: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
    has_many :questions
    has_many :likes, dependent: :destroy
    has_many :liked_question, through: :likes, source: :question

   attachment :image
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :questions
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :question
  belongs_to :customer
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :choices, dependent: :destroy
	has_many :likes
	has_many :question_tags
	accepts_nested_attributes_for :choices #question作成時にchoiceも同時生成
	belongs_to :customer, optional: true
	belongs_to :genre
	attachment :image

	enum is_allowed:{
		許可待ち: 0,
		不許可: 1,
		許可: 2,
	}, _suffix: true
end

app/models/question_tag.rb
class QuestionTag < ApplicationRecord
	belongs_to :question
	belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :question_tags
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
	before_action :authenticate_admin!
	def index
		@genres = Genre.all
		@genre = Genre.new
	end

	def create
		@genre = Genre.new(genre_params)
		@genres = Genre.all
		if @genre.save
		   redirect_back(fallback_location: root_path)
		else
		   render :index
		end
	end

	def edit
		@genre = Genre.find(params[:id])
	end

	def update
		@genre = Genre.find(params[:id])
		@genre.update(genre_params)
		redirect_to admin_genres_path
	end

	private
    def genre_params
    	params.require(:genre).permit(:name)
    end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
	before_action :authenticate_admin!
	def new
		@question = Question.new
		4.times do |n|
			@question.choices.build #buildメソッド(newと似たようなもの)
	    end
	end

	def create
		@question = Question.new(question_params)
		if @question.save
			redirect_to admin_questions_path
		else
			redirect_back(fallback_location: root_path)
		end
	end

	def index
		@q = Question.ransack(params[:q])
		@genres = Genre.all
		@tags = Tag.all
		# もしURLに[:genre_id]が含まれていたら
        if params[:genre_id]
            # その[:genre_id]のデータをGenreから@genreに格納
            @genre = Genre.find(params[:genre_id])
            # @genreに紐付いたクイズを表示
            @question = @genre.questions.page(params[:page]).per(5).order(id: "DESC").where(is_allowed: "許可")
        elsif params[:tag_id]# tag_idがあれば
        	question_tags = QuestionTag.where(tag_id: params[:tag_id])
			question_ids = []
			question_tags.each do |question_tag|
			  question_ids.push(question_tag.question.id)
			end
			@question = Question.where(id: question_ids).page(params[:page]).per(5).order(id: "DESC").where(is_allowed: "許可")
        else
            @question = @q.result.page(params[:page]).per(5).order(id: "DESC").where(is_allowed: "許可")#検索結果を新しいものから表示
        end
	end

	def allow
		@q = Question.ransack(params[:q])
		@genres = Genre.all
		# もしURLに[:genre_id]が含まれていたら
        if params[:genre_id]
            # その[:genre_id]のデータをGenreから@genreに格納
            @genre = Genre.find(params[:genre_id])
            # @genreに紐付いたクイズを表示
            @question = @genre.questions.page(params[:page]).per(5).order(id: "DESC").where(is_allowed: "許可")
        elsif params[:tag_id]# tag_idがあれば
        	question_tags = QuestionTag.where(tag_id: params[:tag_id])
			question_ids = []
			question_tags.each do |question_tag|
			  question_ids.push(question_tag.question.id)
			end
			@question = Question.where(id: question_ids).page(params[:page]).per(5).order(id: "DESC").where(is_allowed: "許可")
        else
            @question = @q.result.page(params[:page]).order(id: "DESC").where(is_allowed: "許可待ち")#検索結果を新しいものから表示
        end
	end

	def search
		@q = Question.search(search_params)
		@genres = Genre.all
		@question = @q.result.order(id: "DESC")
	end

	def edit
		@question = Question.find(params[:id])
	end

	def update
		@question = Question.find(params[:id])
		@question.update(question_params)
		redirect_to admin_questions_path
	end

	private
	def question_params
		params.require(:question).permit(:image, :content, :comment, :genre_id, :is_allowed, choices_attributes: [:id, :sentence, :is_answer, :question_id])
	end
	def search_params
		params.require(:q).permit!
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
	def after_sign_in_path_for(resource)#ログイン後のpassを指定
		if customer_signed_in?#会員ならば
    	   public_customer_path(resource)
    	else
    	   admin_questions_path#管理者ならば
        end
    end

    def after_sign_out_path_for(resource)
		root_path(resource)
	end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :set_question

    def create
      @like = Like.create(customer_id: current_customer.id, question_id: @question.id)
      @question = Question.find(params[:question_id])
    end

    def destroy
      @like = Like.find_by(customer_id: current_customer.id, question_id: @question.id)
      @like.destroy
    end

    private
    def set_question
      @question = Question.find(params[:question_id])
    end
end

app/helpers/admin/choices_helper.rb
module Admin::ChoicesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/admin/questions/allow.html.erb
<div class="row">
	<div class="main-top"></div>
	<div class="col-xs-2 col-xs-offset-1" style="margin-top: 30px">
		<div>
			<%= search_form_for(@q, url:public_questions_search_path) do |f| %>
			    <div>
					<%= f.search_field :content_cont %>
				</div>
				<div>
					<%= f.submit "検索" %>
				</div>
			<% end %>
		</div>
		<div style="margin-top: 20px;">
			<strong style="font-size: large;">ジャンル検索</strong>
		</div>
		<% @genres.each do |genre| %>
			<div class="col-xs-12">
				<%= link_to admin_genre_questions_path(genre) do %>
				<div class="genre-name"><%= genre.name %></div>
	    		<% end %>
			</div>
		<% end %>
	</div>
	<div class="col-xs-6" style="margin-top: 30px;">
		<P class="title">許可待ちクイズ一覧</P>
		<div>
			<% @question.each do |question| %>
			    <div class="question-solve">
			    	<div>
    					<%= attachment_image_tag question, :image, class: "img-square", size:"300x200" %>
					</div>
			    	<div class="question-content">
			    		Q.
			    		<%= question.content %>
			    	</div>
			    	<div>
			    		<% question.choices.each do |choice| %>
			    			<div class="check btn btn-info btn-block question-choice">
			    		    	<%= choice.sentence %>
			    		    	<% if choice.is_answer == true %>
			    		    	<div style="margin: 0 0 0 auto;">正答</div>
			    		    	<% end %>
			    		    </div>
			    		<% end %>
			    	</div>
			    	<div class="row">
			    		<div class="question-genre col-xs-3">
			    			<%= question.genre.name %>
			    		</div>
			    		<% question.question_tags.each do |question_tag| %>
                      		<div class="question-tag"><%= question_tag.tag.name %></div>
                    	<% end %>
			    	</div>
			    	<div class="comment question-comment">
			    		<!-- 自分で作ったクイズの解説は非表示しない -->
			    		解説<br>
			    		<%= question.comment %><br>
			    		<%= link_to "編集する", edit_admin_question_path(question), {class: 'btn btn-success'} %>
			    		<%= form_for [:admin, question] do |f| %>
						<%= f.select :is_allowed, Question.is_alloweds.keys.to_a %>
						<%= f.submit '更新' , {class: 'btn btn-primary'} %>
						<% end %>
			    	</div>
			    </div>
			<% end %>
			<%= paginate @question %>
		</div>
	</div>
	<div class="col-xs-2">
		<div style="margin-top: 20px;">
			<strong style="font-size: large;">タグ検索</strong>
		</div>
		<% @tags.each do |tag| %>
			<div class="col-xs-12">
				<%= link_to admin_tag_questions_path(tag) do %>
					<div class="tag-name"><%= tag.name %></div>
				<% end %>
			</div>
		<% end %>
	</div>
</div>
<div class="main-bottom"></div>

app/views/admin/questions/edit.html.erb
<div class="row">
	<div class="main-top"></div>
	<div class="col-xs-6 col-xs-offset-3">
		<p>クイズ修正</p>
		<div class="row">
		    <%= form_for(@question, url: admin_questions_path) do |f| %>
		    	<div style="margin-bottom: 30px;">
        			<div class="question-image">
        				<label>問題画像<br>
        				       （画像が必要なクイズのみ<br>
        				       選択してください）</label>
        				<%= attachment_image_tag @question, :image, class: "img-square", fallback: "no_image.jpg", size:"300x200" %>
      　				</div>
      				<div style="margin-left: 25%;">
        				<%= f.attachment_field :image %>
        			</div>
    			</div>
		        <div class="form-group">
		    	    <label class="col-xs-2">問題文</label>
		    	    <div class="col-xs-10">
		    	    	<%= f.text_area :content,{class: 'question-form'} %>
		    		</div>
		        </div>
		        <div class="col-xs-10">
		        	<p style="margin-top: 20px;">
		        		＊正解の選択肢には正答ボタンにチェックを入れて下さい。
		        	</p>
		        </div>
		        <%= f.fields_for :choices do |i| %><!--choiceテーブルに保存-->
		        
		        <div class="form-group row">
		        	<div class="col-xs-2" style="margin-left: 15px; ">
		        		<%= i.label :sentence, "選択肢#{i.index+1}" %>
		        	</div>
		        	<div class="col-xs-7">
		        		<%= i.text_area :sentence,{class: 'choice-form'} %>
		        	</div>
		        	<div class="col-xs-2">
		        		<%= i.radio_button :is_answer, :true %>
			        	<%= i.label :is_answer, "正" %>
			        	<%= i.radio_button :is_answer, :false %>
			        	<%= i.label :is_answer, "誤" %>
			        </div>
		        </div>
		        <% end %>

		        <div class="form-group">
		        	<div class="col-xs-2">
		        		<%= f.label :comment, "解説" %>
		        	</div>
		        	<div class="col-xs-10">
		        		<%= f.text_area :comment,{class: 'question-form'} %>
		        	</div>
		        </div>
		        <div class="form-group">
		        	<div class="col-xs-2">
		        		<%= f.label :genre_id, "ジャンル" %>
		        	</div>
		        	<div class="col-xs-5">
		        		<%= f.collection_select(:genre_id, Genre.all, :id, :name, promote: "選択してください") %>
		        	</div>
		        </div>
		        <div class="form-group col-xs-10" style="margin-top: 30px;">
		        	<%= f.submit "修正する",{class: 'btn btn-primary'} %>
		        </div>
		    <% end %>
	    </div>
	</div>
</div>
<div class="main-bottom"></div>

<script type="text/javascript">
$(function(){
    // inputのidから情報の取得
    $('#question_image').on('change', function (e) {
// ここから既存の画像のurlの取得
    var reader = new FileReader();
    reader.onload = function (e) {
        console.log(e.target.result)
        $(".image").attr('src', e.target.result);
    }
// ここまで
    reader.readAsDataURL(e.target.files[0]); //取得したurlにアップロード画像のurlを挿入
});
});

</script>

app/views/admin/questions/index.html.erb
<div class="row">
	<div class="main-top"></div>
	<div class="col-xs-2 col-xs-offset-1" style="margin-top: 30px">
		<div>
			<%= search_form_for(@q, url:public_questions_search_path) do |f| %>
			    <div>
					<%= f.search_field :content_cont %>
				</div>
				<div>
					<%= f.submit "検索" %>
				</div>
			<% end %>
		</div>
		<div style="margin-top: 20px;">
			<strong style="font-size: large;">ジャンル検索</strong>
		</div>
		<% @genres.each do |genre| %>
			<div class="col-xs-12">
				<%= link_to admin_genre_questions_path(genre) do %>
				<div class="genre-name"><%= genre.name %></div>
	    		<% end %>
			</div>
		<% end %>
	</div>
	<div class="col-xs-6" style="margin-top: 30px;">
		<P class="title">新着クイズ一覧</P>
		<div>
			<% @question.each do |question| %>
			    <div class="question-solve">
			    	<div>
    					<%= attachment_image_tag question, :image, class: "img-square", size:"300x200" %>
					</div>
			    	<div class="question-content">
			    		Q.
			    		<%= question.content %>
			    	</div>
			    	<div>
			    		<% question.choices.each do |choice| %>
			    			<div class="check btn btn-info btn-block question-choice">
			    		    	<%= choice.sentence %>
			    		    	<% if choice.is_answer == true %>
			    		    	<div style="margin: 0 0 0 auto;">正答</div>
			    		    	<% end %>
			    		    </div>
			    		<% end %>
			    	</div>
			    	<div class="row">
			    		<div class="question-genre col-xs-3">
			    			<%= question.genre.name %>
			    		</div>
			    		<% question.question_tags.each do |question_tag| %>
                      		<div class="question-tag"><%= question_tag.tag.name %></div>
                    	<% end %>
			    	</div>
			    	<div class="comment question-comment">
			    		<!-- 自分で作ったクイズの解説は非表示しない -->
			    		解説<br>
			    		<%= question.comment %><br>
			    		<%= link_to "編集する", edit_admin_question_path(question), {class: 'btn btn-success'} %>
			    		<%= form_for [:admin, question] do |f| %>
						<%= f.select :is_allowed, Question.is_alloweds.keys.to_a %>
						<%= f.submit '更新' , {class: 'btn btn-primary'} %>
						<% end %>
			    	</div>
			    </div>
			<% end %>
			<%= paginate @question %>
		</div>
	</div>
	<div class="col-xs-2">
		<div style="margin-top: 20px;">
			<strong style="font-size: large;">タグ検索</strong>
		</div>
		<% @tags.each do |tag| %>
			<div class="col-xs-12">
				<%= link_to public_tag_questions_path(tag) do %>
					<div class="tag-name"><%= tag.name %></div>
				<% end %>
			</div>
		<% end %>
	</div>
</div>
<div class="main-bottom"></div>

app/views/admin/questions/new.html.erb
<div class="row">
	<div class="main-top"></div>
	<div class="col-xs-6 col-xs-offset-3">
		<p>新規クイズ作成</p>
		<div class="row">
		    <%= form_for(@question, url: admin_questions_path) do |f| %>
		    	<div style="margin-bottom: 30px;">
        			<div class="question-image">
        				<label>問題画像<br>
        				       （画像が必要なクイズのみ<br>
        				       選択してください）</label>
        				<%= attachment_image_tag @question, :image, class: "img-square", fallback: "no_image.jpg", size:"300x200" %>
      　				</div>
      				<div style="margin-left: 25%;">
        				<%= f.attachment_field :image %>
        			</div>
    			</div>
		        <div class="form-group">
		    	    <label class="col-xs-2">問題文</label>
		    	    <div class="col-xs-10">
		    	    	<%= f.text_area :content,{class: 'question-form'} %>
		    		</div>
		        </div>
		        <div class="col-xs-10">
		        	<p style="margin-top: 20px;">
		        		＊正解の選択肢には正答ボタンにチェックを入れて下さい。
		        	</p>
		        </div>
		        <%= f.fields_for :choices do |i| %><!--choiceテーブルに保存-->
		        
		        <div class="form-group row">
		        	<div class="col-xs-2" style="margin-left: 15px; ">
		        		<%= i.label :sentence, "選択肢#{i.index+1}" %>
		        	</div>
		        	<div class="col-xs-7">
		        		<%= i.text_area :sentence,{class: 'choice-form'} %>
		        	</div>
		        	<div class="col-xs-2">
		        		<%= i.radio_button :is_answer, :true %>
			        	<%= i.label :is_answer, "正" %>
			        	<%= i.radio_button :is_answer, :false %>
			        	<%= i.label :is_answer, "誤" %>
			        </div>
		        </div>
		        <% end %>

		        <div class="form-group">
		        	<div class="col-xs-2">
		        		<%= f.label :comment, "解説" %>
		        	</div>
		        	<div class="col-xs-10">
		        		<%= f.text_area :comment,{class: 'question-form'} %>
		        	</div>
		        </div>
		        <div class="form-group">
		        	<div class="col-xs-2">
		        		<%= f.label :genre_id, "ジャンル" %>
		        	</div>
		        	<div class="col-xs-5">
		        		<%= f.collection_select(:genre_id, Genre.all, :id, :name, promote: "選択してください") %>
		        	</div>
		        </div>
		        <div class="form-group col-xs-10" style="margin-top: 30px;">
		        	<%= f.submit "作成する",{class: 'btn btn-primary'} %>
		        </div>
		    <% end %>
	    </div>
	</div>
</div>
<div class="main-bottom"></div>

<script type="text/javascript">
$(function(){
    // inputのidから情報の取得
    $('#question_image').on('change', function (e) {
// ここから既存の画像のurlの取得
    var reader = new FileReader();
    reader.onload = function (e) {
        console.log(e.target.result)
        $(".image").attr('src', e.target.result);
    }
// ここまで
    reader.readAsDataURL(e.target.files[0]); //取得したurlにアップロード画像のurlを挿入
});
});

</script>

app/views/admin/questions/today.html.erb
<div>
	<div>
		<p>
			本日の許可待ちクイズ<%= @question.count %>件
		</p>
	</div>
</div>