config/routes.rb
Rails.application.routes.draw do
  root "homes#top"
  get "/about" => "homes#about"
  get "public/questions/search" => "public/questions#search"
  post 'questions/:question_id/likes' => "likes#create"
  delete 'questions/:question_id/likes' => "likes#destroy"

  #deviseのcontrollerを二つ作ったため、それぞれのルーティングが必要
  devise_for :admins, :controllers => {
    :sessions => 'admin/devise/sessions'
  }
  devise_for :customers, :controllers => {
    :sessions => 'public/devise/sessions',
    :registrations => 'public/devise/registrations'
  }

#namespaceを用いてpublicとadminのルーティングを指定
    namespace :public do
    	resources :questions, only: [:index, :new, :create, :update, :edit]
    	resources :choices
      resources :customers
      get "customers/like/customer_id" => "customers#like"
      resources :genres, only: [:index] do
        resources :questions, only: [:index]
      end
      resources :tags, only: [:index] do
        resources :questions, only: [:index]
      end
    end 


    namespace :admin do
      get "questions/allow" => "questions#allow"
    	resources :questions, only: [:index, :new, :create, :update, :edit]
    	resources :choices
      resources :customers, only: [:index, :show]
      resources :genres, only: [:index, :create, :edit, :update] do
        resources :questions, only: [:index]
      end
      resources :tags, only: [:index] do
        resources :questions, only: [:index]
      end
    end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
	belongs_to :question, optional: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
    has_many :questions
    has_many :likes, dependent: :destroy
    has_many :liked_question, through: :likes, source: :question

   attachment :image
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :questions
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :question
  belongs_to :customer
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :choices, dependent: :destroy
	has_many :likes
	has_many :question_tags
	accepts_nested_attributes_for :choices #question作成時にchoiceも同時生成
	belongs_to :customer, optional: true
	belongs_to :genre
	attachment :image

	enum is_allowed:{
		許可待ち: 0,
		不許可: 1,
		許可: 2,
	}, _suffix: true
end

app/models/question_tag.rb
class QuestionTag < ApplicationRecord
	belongs_to :question
	belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :question_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
	def after_sign_in_path_for(resource)#ログイン後のpassを指定
		if customer_signed_in?#会員ならば
    	   public_customer_path(resource)
    	else
    	   admin_questions_path#管理者ならば
        end
    end

    def after_sign_out_path_for(resource)
		root_path(resource)
	end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :set_question

    def create
      @like = Like.create(customer_id: current_customer.id, question_id: @question.id)
      @question = Question.find(params[:question_id])
    end

    def destroy
      @like = Like.find_by(customer_id: current_customer.id, question_id: @question.id)
      @like.destroy
    end

    private
    def set_question
      @question = Question.find(params[:question_id])
    end
end

app/helpers/admin/choices_helper.rb
module Admin::ChoicesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/layouts/_admin_header.html.erb
<div class="container" style="width: 100%;">
	<div class="row header-style">
		<div class="col-xs-3 col-xs-offset-1" style="margin-top: 1%">
			<%= link_to root_path do %>
				<%= image_tag "logo.png", size: '195x65', alt: "The Forest Of Quiz" %>
			<% end %>管理者サイト
		</div>
		<% if admin_signed_in? %>
			<div class="col-xs-1 col-xs-offset-2 header-item" style="padding-left: 2%;">
			    <%= link_to "会員一覧", admin_customers_path %>
			</div>
			<div class="col-xs-1 header-item">
				<%= link_to "申請中Quiz", admin_questions_allow_path %>
			</div>
			<div class="col-xs-1 header-item" style="padding-left: 1.5%;">
			    <%= link_to "クイズ一覧", admin_questions_path %>
			</div>
			<div class="col-xs-1 header-item" style="padding-left: 2%;">
			    <%= link_to "ジャンル", admin_genres_path %>
			</div>
			<div class="col-xs-1 header-item" style="padding-left: 1.5%;">
			    <%= link_to "ログアウト",destroy_admin_session_path, method: :delete %>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/_customers_header.html.erb
<div class="container" style="width: 100%;">
	<div class="row header-style">
		<div class="col-xs-3 col-xs-offset-1" style="margin-top: 1%">
			<%= link_to root_path do %>
				<%= image_tag "logo.png", size: '195x65', alt: "The Forest Of Quiz" %>
			<% end %>
		</div>
		<% if customer_signed_in? %>
		    <!--<p class="col-xs-3">ようこそ<%= current_customer.name %>さん</p>-->
		    <div class="col-xs-1 col-xs-offset-2 header-item" style="padding-left: 2.5%;">
		    	<%= link_to "About", about_path %>
			</div>
			<div class="col-xs-1 header-item" style="padding-left: 2%;">
				<%= link_to "Quiz一覧", public_questions_path %>
			</div>
		    <div class="col-xs-1 header-item" style="padding-left: 1.5%;">
		    	<%= link_to "マイページ", public_customer_path(current_customer) %>
		    </div>
		    <div class="col-xs-1 header-item" style="padding-left: 1.5%;">
		    	<%= link_to "いいね一覧", public_customers_like_customer_id_path(current_customer) %>
		    </div>
		    <div class="col-xs-1 header-item" style="padding-left: 1.5%;">
		    	<%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
		    </div>
		<% else %>
			<div class="col-xs-1 col-xs-offset-3 header-item" style="padding-left: 2.5%;">
		    	<%= link_to "About", about_path %>
			</div>
			<div class="col-xs-1 header-item" style="padding-left: 2%;">
				<%= link_to "Quiz一覧", public_questions_path %>
			</div>
			<div class="col-xs-1 header-item" style="padding-left: 2%;">
		    	<%= link_to "会員登録", new_customer_registration_path %>
		    </div>
		    <div class="col-xs-1 header-item" style="padding-left: 2%;">
		    	<%= link_to "ログイン", new_customer_session_path %>
			</div>		    		
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheForestOfQuiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar-fixed-top">
      <% if request.fullpath.include? "admin" %><!--　管理者なら -->
        <%= render 'layouts/admin_header' %>
      <% else %><!--　会員なら -->
        <%= render 'layouts/customers_header' %>
      <% end %>
    </header>
    <main>
      <div style="margin-top: 83px"></div>
      <div class="container" style="width: 100%;">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/publics/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/publics/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>